import ExportHistoryCard from "./ExportHistoryCard";
import SectionHeader from "./SectionHeader";

const exports = [
    { id: "EXP-001", file: "daily-health-report.pdf", format: "PDF", by: "Clinic Admin", time: "Today, 9:18 AM", status: "Completed" },
    { id: "EXP-002", file: "weekly-alerts.xlsx", format: "Excel", by: "Health Kiosk", time: "Today, 8:44 AM", status: "Completed" },
    { id: "EXP-003", file: "bmi-summary.pdf", format: "PDF", by: "Clinic Admin", time: "Yesterday, 3:30 PM", status: "Queued" },
];

export default function RecentExportsTable() {
    return (
        <section className="rounded-[14px] border p-5 shadow-xl" style={{ backgroundColor: "var(--color-card)", borderColor: "var(--color-border)" }}>
            <SectionHeader title="Recent exports" description="Demo export history for generated report files." />
            <div className="mt-4 overflow-auto rounded-[12px] border" style={{ borderColor: "var(--color-border)" }}>
                <table className="w-full min-w-[760px] text-left text-sm">
                    <thead style={{ backgroundColor: "var(--color-surface)", color: "var(--color-muted)" }}>
                        <tr>{["Export ID", "File Name", "Format", "Generated By", "Export Time", "Status"].map((column) => <th key={column} className="border-b px-3 py-3 font-black" style={{ borderColor: "var(--color-border)" }}>{column}</th>)}</tr>
                    </thead>
                    <tbody>{exports.map((item) => <ExportHistoryCard key={item.id} item={item} />)}</tbody>
                </table>
            </div>
        </section>
    );
}
