import Pagination from "./Pagination";
import ReportTableRow from "./ReportTableRow";
import SectionHeader from "./SectionHeader";

const columns = ["Report ID", "Report Name", "Date Range", "Generated By", "Role Filter", "Measurement Type", "Total Records", "Export Format", "Generated At", "Status", "Actions"];

export default function ReportsTable({ reports = [], onPreview }) {
    return (
        <section className="rounded-[14px] border p-5 shadow-xl" style={{ backgroundColor: "var(--color-card)", borderColor: "var(--color-border)" }}>
            <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
                <SectionHeader title="Generated reports" description="Clinic report history, export status, and preview controls." />
                <span className="rounded-full border px-3 py-1 text-xs font-black" style={{ borderColor: "var(--color-border)", color: "var(--color-muted)" }}>Demo reporting data</span>
            </div>
            <div className="max-h-[34rem] overflow-auto rounded-[12px] border" style={{ borderColor: "var(--color-border)" }}>
                <table className="w-full min-w-[1220px] text-left text-sm">
                    <thead className="sticky top-0 z-10" style={{ backgroundColor: "var(--color-surface)", color: "var(--color-muted)" }}>
                        <tr>
                            {columns.map((column) => <th key={column} className="border-b px-3 py-3 font-black" style={{ borderColor: "var(--color-border)" }}>{column}</th>)}
                        </tr>
                    </thead>
                    <tbody>
                        {reports.map((report) => <ReportTableRow key={report.id} report={report} onPreview={onPreview} />)}
                    </tbody>
                </table>
            </div>
            <div className="mt-4">
                <Pagination />
            </div>
        </section>
    );
}
