<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>@yield('title')</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 12px;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #2563eb;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 20px;
            color: #1e3a8a;
            text-transform: uppercase;
        }
        .header p {
            margin: 5px 0 0;
            font-size: 14px;
            color: #475569;
        }
        .metadata {
            display: table;
            width: 100%;
            margin-bottom: 20px;
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
            padding: 10px;
            border-radius: 4px;
        }
        .metadata-col {
            display: table-cell;
            width: 50%;
            vertical-align: top;
        }
        .metadata h3 {
            margin-top: 0;
            font-size: 12px;
            text-transform: uppercase;
            color: #64748b;
        }
        .metadata ul {
            list-style: none;
            padding: 0;
            margin: 0;
        }
        .metadata li {
            margin-bottom: 4px;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        table.data-table th, table.data-table td {
            border: 1px solid #cbd5e1;
            padding: 8px;
            text-align: left;
        }
        table.data-table th {
            background-color: #f1f5f9;
            font-weight: bold;
            color: #334155;
            text-transform: uppercase;
            font-size: 11px;
        }
        table.data-table tr:nth-child(even) {
            background-color: #f8fafc;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #94a3b8;
            border-top: 1px solid #e2e8f0;
            padding-top: 10px;
        }
        .status-badge {
            display: inline-block;
            padding: 3px 6px;
            border-radius: 4px;
            font-size: 10px;
            font-weight: bold;
            color: white;
            text-transform: uppercase;
        }
        .bg-green { background-color: #10b981; }
        .bg-red { background-color: #ef4444; }
        .bg-yellow { background-color: #f59e0b; }
        .bg-blue { background-color: #3b82f6; }
    </style>
</head>
<body>

    <div class="header">
        <h1>Health Kiosk System</h1>
        <p>@yield('title')</p>
    </div>

    <div class="metadata">
        <div class="metadata-col">
            <h3>Report Information</h3>
            <ul>
                <li><strong>Generated By:</strong> {{ $adminName }}</li>
                <li><strong>Date Generated:</strong> {{ $dateGenerated }}</li>
                <li><strong>Total Records:</strong> {{ count($data) }}</li>
            </ul>
        </div>
        <div class="metadata-col">
            <h3>Filters Applied</h3>
            <ul>
                @if($filters['date_from']) <li><strong>From:</strong> {{ $filters['date_from'] }}</li> @endif
                @if($filters['date_to']) <li><strong>To:</strong> {{ $filters['date_to'] }}</li> @endif
                @if($filters['department']) <li><strong>Department:</strong> {{ $filters['department'] }}</li> @endif
                @if(!empty($filters['program'])) <li><strong>Program:</strong> {{ implode(', ', $filters['program']) }}</li> @endif
                @if(!empty($filters['strand'])) <li><strong>Strand:</strong> {{ implode(', ', $filters['strand']) }}</li> @endif
                @if(!empty($filters['year_level'])) <li><strong>Year:</strong> {{ implode(', ', $filters['year_level']) }}</li> @endif
                @if(!empty($filters['grade_level'])) <li><strong>Grade:</strong> {{ implode(', ', $filters['grade_level']) }}</li> @endif
                @if($filters['gender']) <li><strong>Gender:</strong> {{ ucfirst($filters['gender']) }}</li> @endif
            </ul>
        </div>
    </div>

    @if(count($data) > 0)
        @yield('content')
    @else
        <div style="text-align: center; padding: 50px; background-color: #f8fafc; border: 1px dashed #cbd5e1;">
            <h2 style="color: #64748b; margin: 0;">No records found.</h2>
            <p style="color: #94a3b8; margin-top: 10px;">There is no data matching the applied filters.</p>
        </div>
    @endif

    <div class="footer">
        Generated by the Health Kiosk Capstone System &copy; {{ date('Y') }}
    </div>

</body>
</html>
